export default [
    ["Geodesic", "01_Geodesic.html"],
    "Rotation",
    ["Pattern", "03_Pattern.html"],
    "Sound",
    ["Monochromatic", "05_Monochromatic.html"],
    "Three",
    ["Painting", "https://julesfouchy.github.io/impressionist-repainter/"],
    "Vasarely",
    "Diffusion",
    "Sine Wave",
    "Cube",
    "L-system",
    "Sky",
    "Chaos",
    "Infinity",
    "Light",
    "Motion",
    ["Tiles", "https://julesfouchy.github.io/Tiles_ProgTober2020/"],
    "Alignment",
    ["Fractal", "https://julesfouchy.github.io/ProgTober2020_Fractal/"],
    "Blur",
    "Inverted",
    "Negative",
    "Particles",
    "Ray",
    "Snow",
    "Circles",
    "Tree",
    "Symmetry",
    "Distortion",
    "Fireworks",
    //"Repetition",
    //"Rosace",
    //"Calm",
]