export default [
    ["Geodesic", "01_Geodesic.html"],
    ["Rotation", "https://www.shadertoy.com/view/3sycDy"],
    ["Pattern", "03_Pattern.html"],
    "Sound",
    ["Monochromatic", "05_Monochromatic.html"],
    ["Three", "06_Three.html"],
    ["Painting", "https://julesfouchy.github.io/impressionist-repainter/"],
    ["Vasarely", "08_Vasarely.html"],
    "Diffusion",
    ["Sine Wave", "10_SineWave.html"],
    ["Cube", "11_Cube.html"],
    ["L-system", "12_LSystem.html"],
    ["Sky", "13_Sky.html"],
    "Chaos",
    "Infinity",
    "Light",
    "Motion",
    ["Tiles", "https://julesfouchy.github.io/Tiles_ProgTober2020/"],
    ["Alignment", "19_Alignment"],
    ["Fractal", "https://julesfouchy.github.io/ProgTober2020_Fractal/"],
    "Blur",
    ["Inverted", "22_Inverted.html"],
    ["Negative", "https://julesfouchy.github.io/ProgTober2020_Negative/"],
    "Particles",
    "Ray",
    "Snow",
    "Circles",
    "Tree",
    "Symmetry",
    ["Distortion", "30_Distortion.html"],
    "Fireworks",
    //"Repetition",
    //"Rosace",
    //"Calm",
]